= {product} - Hist칩rias de Usuario
Universidad Cat칩lica Boliviana. 
1.0.0
:product: BOT CLUB DE VIDEOS

## Introducci칩n
El presente documentO tendr치 el detalle de todas las histor칤as de usuario para la construcci칩n de un BOT de CLUB DE VIDEOS.

Se ha establecido que la funcionalidad m칤nima para la implementaci칩n ser치:

Para el club de videos:

    1. Registrar un video con fotograf칤as, actores, genero, a침o, premios.
    2. Registrar el alquiler un video.
    3. Registrar la perdida o no devoluci칩n de un video.
    4. Revisar los videos que est치n pendientes de devoluci칩n.
    5. Listado de pel칤culas pendientes de entrega.

Para los clientes:

     1. Buscar pel칤culas por nombre, t칤tulo, actores, g칠neros o premios.
     2. Reservar una pel칤cula simulando un m칠todo pago.

## Historias de Usuario.

### 100 - Buscar pel칤culas

*Autor*: Juan Mauricio Illanes Chipana

*Fecha*: 7/03/2022

*Prioridad*: ALTA

#### Descripci칩n


Como `Cliente` del club de videos, necesito conocer las pel칤culas que se encuentran disponibles en el club, quiero realizar la b칰squeda de una pel칤cula con base en su `t칤tulo`, alg칰n `actor` que act칰e en ella, `generos` o `premios`. Adicionalmente, quiero saber si las pel칤culas est치n agotadas o disponibles, adem치s 칠l `BOT` debe tomar en cuenta los siguientes aspectos:

 * La disponibilidad de las pel칤culas
 * Las fotograf칤as de cada una de las pel칤culas que se consulten
 * La clasificaci칩n de la pel칤cula que se consulte
 * Nombres de los actores(aunque sea sin el apellido)
 * Numero de premios obtenidos registrados

La b칰squeda pasar치 pos los siguientes estados:

  * *SOLICITADO*: Cuando el cliente env칤a su consulta al BOT y el BOT no la rechaza.
  * *EXITO*: Cuando el BOT muestra el resultado de la b칰squeda.
  * *FALLIDO*: Solicitud rechazada por club
  * *NO VALIDO*: El cliente introduce caracteres no validos

El diagrama de estados para la `BUSQUEDA` ser치:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml
[*] --> SOLICITADO
SOLICITADO --> EXITO
EXITO --> [*]
SOLICITADO -> FALLIDO
FALLIDO --> [*]
SOLICITADO -> NO_VALIDO
NO_VALIDO --> [*]
@enduml
....

#### Escenarios
1. El cliente no introduce bien el nombre de la pel칤cula.
2. El cliente hace b칰squedas en dias que no se hizo inventario.
3. Pel칤culas solicitadas al mismo tiempo.

#### Casos de Prueba

*100.1.1 Buscar por titulo*

Descripci칩n: Se prueba la respuesta del sistema cuando el usuario busca una pel칤cula con base en su t칤tulo.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando /hola
    - Datos: comando /hola
    - Resultado esperado: El BOT retorna un mensaje. "Hola puedes buscar tu pel칤cula por:" mostrando diferentes categorias(actor, t칤tulo, premios, g칠nero).
 2. El cliente busca una pelicula por su titulo
    - Datos: coloca `Titulo`
    - Resultado esperado: El BOT retorna un mensaje. "Esta bien, introduzca el nombre del titulo:".
 3. El `BOT` muestra la lista de peliculas
    - Datos: coloca `Star wars`
    - Resultado esperado: El BOT retorna una lista de todas las peliculas bajo ese nombre.


*100.1.2 Buscar por actor*

Descripci칩n: Se prueba la respuesta del sistema cuando el usuario busca una pel칤cula en base a su actor.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando /hola
    - Datos: comando /hola
    - Resultado esperado: El BOT retorna un mensaje. "Hola puedes buscar tu pelicula por:" mostrando diferentes categorias(actor, t칤tulo, premios, g칠nero).
 2. El cliente busca una pelicula por su actor
    - Datos: coloca `Actor`
    - Resultado esperado: El BOT retorna un mensaje. "Esta bien, introduzca el nombre del actor:".
 3. El `BOT` muestra la lista de peliculas
    - Datos: coloca `DWAYNE JOHNSON`
    - Resultado esperado: El BOT retorna una lista de todas las peliculas bajo ese actor.

*100.1.3 Buscar por genero*

Descripci칩n: Se prueba la respuesta del sistema cuando el usuario busca una pel칤cula en base a su genero.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando /hola
    - Datos: comando /hola
    - Resultado esperado: El BOT retorna un mensaje. "Hola puedes buscar tu pelicula por:" mostrando diferentes categorias(actor, t칤tulo, premios, g칠nero).
 2. El cliente busca una pelicula por su genero
    - Datos: coloca `Genero`
    - Resultado esperado: El BOT retorna un mensaje. "Esta bien, introduzca el nombre del genero:".
 3. El `BOT` muestra la lista de peliculas
    - Datos: coloca `Terror`
    - Resultado esperado: El BOT retorna una lista de todas las peliculas bajo ese genero.

*100.1.4 Buscar por premios*

Descripci칩n: Se prueba la respuesta del sistema cuando el usuario busca una pel칤cula en base a sus premios.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando /hola
    - Datos: comando /hola
    - Resultado esperado: El BOT retorna un mensaje. "Hola puedes buscar tu pelicula por:" mostrando diferentes categorias(actor, t칤tulo, premios, g칠nero).
 2. El cliente busca una pelicula por su genero
    - Datos: coloca `Premios`
    - Resultado esperado: El BOT retorna un mensaje. "Esta bien, introduzca el n칰mero de premios:".
 3. El `BOT` muestra la lista de peliculas
    - Datos: coloca `9`
    - Resultado esperado: El BOT retorna una lista de todas las peliculas que tengan esa cantidad de premios.

### 102 - Registro de alquiler de videos

*Autor*: Sergio Fernando Prudencio Veliz

*Fecha*: 08/03/2022

*Prioridad*: MUY ALTA

#### Descripci칩n

Un `Cliente` debe poder solicitar su registro de alquiler en el sistema por medio del BOT, al momento de solicitar su registro, el cliente deber치 enviar la siguiente informaci칩n:

*   Nombre
*   Apellido
*   Email
*   Carnet identidad
*   Titulo Pelicula

Esta informaci칩n es guardara en BBDD y se coloca al cliente en un estado `REGISTRO SOLICITADO`. Luego el `ADMINISTRADOR DE LA TIENDA` recibe la notificaci칩n con la informaci칩n del cliente y procede a aprobar (`REGISTRO APROBADO`) o denegar `REGISTRO DENEGADO` la solicitud.

El diagrama de secuencias para la presente hist칩ria es el siguiente:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml
actor Cliente

Cliente -> BOT: Solicitar reserva alquiler en el sistema
BOT --> Cliente:

actor Empleado
BOT -> Empleado: Nueva solicitud de registro
Empleado --> BOT: Aprobaci칩n/Rechazo
BOT -> Cliente: Notificaci칩n del estado de la solicitud

@enduml
....

#### Escenarios
1. Video Disponible.
2. Video No Disponible.
3. Validaci칩n de datos ingresados por el usuario.

#### Casos de Prueba

*102.1.1 Validaci칩n de par치metros*
Descripci칩n: Al momento de registrarse la reserva, los siguientes campos son obligatorios: Nombres, Primer apellido, email, carnet identidad.

En caso de que el `Cliente no ingrese uno de estos valores` no se debe proceder a enviar la solicitud.

Pasos:

1. Ingresar al BOT via Telegram y enviar el comando /start
- Datos: NINGUNO
- Resultado esperado: El BOT retorna un mensaje. "Bienvenido a la tienda de Videos que desea hacer:"
*  Registro de Alquiler
2. El `Cliente` env칤a el comando `/registrar`
- Datos: comando `/registrar`
- Resultado: El BOT pregunta por el nombre, apellido, email y carnet de identidad del cliente.
3. El `Cliente` coloca o se equivoca e introduce un espacio en blanco o caracter especial.
- Datos: Coloca `un espacion en blanco`
- Resultado: El BOT pide nuevamente el nombre copmleto porque no puede ser espacios en blanco.
4. El `Cliente` coloca car치cteres no convencionales como emojis.
- Datos: Coloca `Sergio Fernando 游`
- Resultado: El BOT le indica que no puede colocar caracteres especiales.

### 102.1 - Solicitud de reserva video.

*Autor*: Sergio Fernando Prudencio Veliz

*Fecha*: 05/03/2022

*Prioridad*: ALTA

#### Descripci칩n
Un `Cliente` debe solicitar la reserva de un video por medio del bot, para esto debe enviar la fecha inicio y fecha fin de la solicitud, titulo de la pelicula, nombre,apellido,email y ci. Una vez enviada su solicitud un `Empleado de la tienda` proceder치 a autorizar o rechazar la solicitud del cliente, en caso de que la `Solicitud` sea rechazada se debe agregar una observaci칩n para que si es que procede el empleado realice las modificaciones correspondientes. Ademas el Bot tendra control de:
* Disponibilidad de los videos en stock
* Tiempo de renta de un video.

La solicitud pasar치 pos los siguientes estados:

* *SOLICITADA*: Cuando el cliente env칤a su solicitud al BOT y el BOT no la rechaza.
* *NO V츼LIDO*: Cuando el cliente env칤a su solicitud al BOT y no cumple con los requisitos del registro, cuando introduce datos erroneos o cuando el video no se encuentra disponible.
* *ACEPTADA*: Solicitud aprobada por persona de la tienda.
* *RECHAZADA*: Solicitud rechazada por personal de la tienda.
* *CANCELADA*: El usuario cancel칩 una reserva solicitada ACEPTADA.

El diagrama de estados para la `SOLICITUD` ser치:

[plantuml, format="png", id="estados-solicitud"]
....
@startuml

[*] --> SOLICITADA
SOLICITADA --> NO_VALIDO
NO_VALIDO --> [*]
SOLICITADA -> ACEPTADA
SOLICITADA -> RECHAZADA
RECHAZADA --> [*]
ACEPTADA -> CANCELADA
ACEPTADA --> [*]
CANCELADA --> [*]

@enduml
....

#### Escenarios

1. Solicitud de reserva.
2. Cancelaci칩n de reserva de video(s).

#### Casos de Prueba

*102.1.1 Usuario solicita reserva de un video no disponible*

Descripci칩n: Un usuario desea obtener una reserva de un video que acaba de pasar de disponible a no disponible

Pasos:

1. Ingresar al BOT via Telegram y enviar el comando /registrar
- Datos: NINGUNO
- Resultado esperado: El BOT retorna un mensaje. "El video ya no se encuentra disponible"

### 103 - Perdida o no devolucion de una pelicula
*Autor*: Damaris Blas

*Fecha*: 08/03/2022

*Prioridad*: ALTA

#### Descripci칩n
Como cliente del club de videos requiero conocer el procedimiento en caso de una perdida o no devolucion de un video. El bot tiene que tener en cuenta:
 * Historial reciente de peliculas prestadas por el cliente
 * El estado de cada pelicula (Devuelto o NO devuelto)
 * Dias de atraso en la devolucion de una pelicula.

### Escenarios
El cliente escribe mal el nombre de la pelicula perdida
El cliente escribe mal su CI


### Casos de prueba
*102.1 Peliculas que no se devolvio*

Descripcion:  Se prueba la respuesta del sistema cuando el cliente busca las peliculas que no devolvio.

Pasos:

1. Ingresar al Bot via Telegram y enviar el ci del cliente
 - Datos: coloca CI
 - Resultado eperado: El Bot retorna un mensaje de bienvenida.

2. El cliente busca las peliculas que no devolvio
- Datos: comando /PeliculasNoDevueltas
- Resultado esperado: El bot retorna una lista de las peliculas que el cliente aun no ha devuelto, tambien mostrara los dias de atraso que se tiene.

*102.2 Peliculas perdidas*
Descripcion: Se prueba la respuesta del sistema cuando un cliente pierde una pelicula.
Pasos:
1. Ingresar al Bot via Telegram y enviar el ci del cliente
 - Datos: coloca CI
 - Resultado eperado: El Bot retorna un mensaje de bienvenida.
2. El cliente busca las peliculas que no devolvio
- Datos: comando /PeliculasNoDevueltas
- Resultado esperado: El bot retorna una lista de las peliculas que el cliente aun no ha devuelto, tambien mostrara los dias de atraso que se tiene.

3. El cliente busca la pelicula que perdio
- Datos: coloca Pelicula no devuelta
- Resulatdo esperado: El bot registrara en el historial del cliente esa pelicula perdida.

